apiVersion: v1
kind: Service
metadata:
  name: file-svc
spec:
  type: LoadBalancer
  selector:
    app: file-svc
  ports:
  - protocol: TCP
    name: file-svc
    port: 30000
    targetPort: 80
    nodePort: 30000